/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Cactus.gltf -o src/components/Cactus.jsx -r public
*/

import React, {useEffect} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Cactus(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/Cactus.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const anim = props.hovered ? 'Dance' : 'Idle';
    actions[anim].reset().fadeIn(0.5).play();

    return () => actions[anim].fadeOut(0.5)
  }, [props.hovered]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="MonsterArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
          <skinnedMesh name="Cactus001" geometry={nodes.Cactus001.geometry} material={materials.Texture} skeleton={nodes.Cactus001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Cactus.gltf')
